
Title = "WMI Exporter Configuration"

[ServiceDiscovery]
    Enabled = true
    RemoteEndpoint = "dev-ucm-con-w2a-a.corporate.t-mobile.com"
    RemotePort = 8500
    Datacenter = "ucm-west"
    ServiceID = "ucm.agent.wmiExporter"
    RegisterServiceName = "dev-mon-agent-ucm"

[MetadataReporting]
    Enabled = true
    AWSRegion = "us-west-2"

[AwsTagsToLabels]
    Enabled = true
    RefreshPeriod = 3600
    [[AwsTagsToLabels.TagsToCapture]]
    	TagName  = ["instanceId"]
	LabelName    = "host"
    MissingLabel = "UNTAGGED"
    [[AwsTagsToLabels.TagsToCapture]]
    	TagName  = ["Application"]
	LabelName    = "application"
    MissingLabel = "UNTAGGED"
    [[AwsTagsToLabels.TagsToCapture]]
    	TagName  = ["Environment"]
	LabelName    = "environment"
    MissingLabel = "UNTAGGED"
    [[AwsTagsToLabels.TagsToCapture]]
    	TagName  = ["Stack","Role"]
	LabelName    = "stack_role"
    MissingLabel = "UNTAGGED"
    MergeSeparator="_"
    [[AwsTagsToLabels.TagsToCapture]]
    	TagName  = ["Name"]
	LabelName    = "name"
    MissingLabel = "UNTAGGED"

[Collectors]
    GoCollectionEnabled = true
    ExporterCollectionEnabled = true
    WmiCollectionEnabled = true
    AgentCollectionEnabled = false
    EnabledCollectors   = "cpu,os"
    MetricTimeout = 2
    [[Collectors.MetricRemap]]
        WmiMetricName = ["test"]
        ExportName = "export_test"
    [[Collectors.MetricRemap]]
        WmiMetricName = ["test2"]
        ExportName = "export_test2"

[Service]
    ListenPort =  9103
    MetricPath = "/metrics"
    CollectionInterval = 60
    ServiceName = "wmi_exporter"
