
Title = "WMI Exporter Configuration"

[ServiceDiscovery]
    Enabled = true
    RemoteEndpoint = "dev-ucm-con-w2a-a.corporate.t-mobile.com"
    RemotePort = 8500
    Datacenter = "ucm-west"
    ServiceID = "ucm.agent.wmiExporter"
    RegisterServiceName = "dev-mon-agent-ucm"

[MetadataReporting]
    Enabled = true
    AWSRegion = "us-west-2"

[AwsTagsToLabels]
    Enabled = true
    RefreshPeriod = 3600

[Collectors]
    GoCollectionEnabled = true
    ExporterCollectionEnabled = true
    WmiCollectionEnabled = true
    AgentCollectionEnabled = false
    EnabledCollectors   = "cpu,os"
    [[Collectors.MetricRemap]]
        WmiMetricName = ["test"]
        ExportName = "export_test"
    [[Collectors.MetricRemap]]
        WmiMetricName = ["test2"]
        ExportName = "export_test2"

[Service]
    ListenPort =  9103
    MetricPath = "/metrics"
    CollectionInterval = 60
    ServiceName = "wmi_exporter"
