
Title = "WMI Exporter Configuration"

[ServiceDiscovery]
    enabled = true
    endpoint = "dev-ucm-con-w2a-a.corporate.t-mobile.com"
    port = 5500
    datacenter = "ucm-west"
    serviceID = "ucm.agent.wmiExporter"

[MetadataReporting]
    enabled = true
    awsregion = "us-west-2"

[AwsTagsToLabels]
    enabled = true
    refreshPeriod = 3600

[Collectors]
    goCollectionEnabled = true
    exporterCollectionEnabled = true
    wmiCollectionEnabled = true
    agentCollectionEnabled = false
    enabledCollectors   = true
    [metricNameMapping.0]
        wmiMetricName = ["test"]
        exportName = "export_test"

[Service]
    listenPort =  9103
    metricPath = "/metrics"
    collectionInterval = 60
    serviceName = "wmi_exporter"
